apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      version: InfluxQL
      httpMode: GET
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Bearer ${INFLUXDB3_TOKEN}
    database: readings
    isDefault: true
